### ISSUE TITLE
Move 500 Page to Storybook

### ISSUE THREAD

**Issue by borabiricik** [BursaBilisimToplulugu/bbt-cms-web#23]
"pages/status/500/index.tsx" file's content should move to Storybook. After moving to Storybook, page should be deleted and link should be removed from left menu.

For reference; you may want to inspect Catalog/Messenger from Storybook.

NOTE: Page should be under Catalog/ExtraPages/<500.stories.tsx>

**Comment by Demir-Utku** [comment]
I can take this task.
